django_practical/ChebiChemblIntegration/ChebiChembl/urls.py
from django.conf.urls import url


from . import views

app_name = 'ChebiChembl'
urlpatterns = [
    url(r'^index/$',views.IndexView.as_view(),name="index"),
    url(r'^results/$',views.ResultsView.as_view(),name="results"),
    url(r'^hello_world/$', views.hello_world),
]

django_practical/ChebiChemblIntegration/ChebiChemblIntegration/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^ChebiChembl/', include('ChebiChembl.urls', namespace="ChebiChembl")),
    url(r'^admin/', admin.site.urls),
]

django_practical/ChebiChemblIntegration/ChebiChembl/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


# Create your models here.

class Question_disease_name(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question_disease_name, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    def __str__(self):
        return self.choice_text


class Post(models.Model):
    #author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

django_practical/ChebiChemblIntegration/ChebiChembl/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

django_practical/ChebiChemblIntegration/ChebiChembl/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from .forms import NameForm
from django.shortcuts import render_to_response, redirect

from .models import Choice, Question_disease_name
import pc_for_disease as pc
import hello as h




from django.http import HttpResponse

def hello_world(request):
    return HttpResponse("Hello, world.")

def disease(request):
        """Generate sorted list of partition coefficients"""
        temp = h.world()
        return HttpResponse("hELLO")


def submit(request):
    info=request.POST['info']
    return render(request, "ChebiChembl/results.html", {"answer": "Hello world"})


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            mymodel = pc.Calculate_PC()

            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'name.html', {'form': form})

class IndexView(generic.ListView):
    template_name = 'ChebiChembl/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set to be
        published in the future)."""
        
        return Question_disease_name.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


    def get_name(request):
        # if this is a POST request we need to process the form data
        if request.method == 'POST':
        # create a form instance and populate it with data from the request:
            form = NameForm(request.POST)
        # check whether it's valid:
            if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
                return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
        else:
            form = NameForm()

        return render_to_response("name.html",  {'form': form,  }, context_instance = RequestContext(request))



class ResultsView(generic.ListView):
    model = Question_disease_name
    template_name = 'ChebiChembl/results.html'

    def disease(request):
        """Generate sorted list of partition coefficients"""
        temp = h.world()
        return render(request, "ChebiChembl/results.html", {"answer": temp})
    #def get_partition_coeff(self):

django_practical/ChebiChemblIntegration/ChebiChembl/templates/ChebiChembl/index.html
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'ChebiChembl/style.css' %}" />
    {% if latest_question_list %}
                <ul>
                {% for question in latest_question_list %}
                     <h1><a href="http://127.0.0.1:8000/ChebiChembl/results/">{{ views.disease }} Enter disease name -</a></h1>
                {% endfor %}
                </ul>
            {% else %}
                <p>No questions are available.</p>
            {% endif %}
</head>
    
<!--<form action= method="post">
    <input type="text" size ="50" >
    <button type="submit">Submit</button>
</form>-->
<form action="http://127.0.0.1:8000/ChebiChembl/results/" method="post">
    <label for="your_name"></label>
    <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
    <input type="submit" value="OK">
</form>
</html>

django_practical/ChebiChemblIntegration/ChebiChembl/templates/ChebiChembl/name.html
<form action="/your-name/" method="post">
    <!--{% csrf_token %}-->
    {{ form }}
    <input type="submit" value="Submit" />
</form>

django_practical/ChebiChemblIntegration/ChebiChembl/templates/ChebiChembl/results.html
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'ChebiChembl/style.css' %}" />
</head>





<ul>
<!--{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul> -->
<body>
<h1>{{ Question_disease_name.question_text }}</h1>
<div>
<p>
CHEMBL compounds along with their Partition Coefficients are - 
    {{ "Hello world" }}
    <!--{%for item in list%}
        <li>{{item}}</li>
    {% endfor %}-->
</p>
</div>
<a href="http://127.0.0.1:8000/ChebiChembl/index/">Check for another disease?</a>
</body>
</html>